### PR TITLE
Issue 40

### PR DESCRIPTION
**Pull request by ros3bud**
I would appreciate some input on this one: @alexkwolfe, @cgrayson 

Is it a good idea to validate the website passed in mortgage.property.url? Or is that overkill? 

Also, there are other numbers passed in this integration where we don't validate them, but at least one where we do validate that it's a number. Ex: https://github.com/activeprospect/leadconduit-integration-leadpoint/blob/master/spec/inbound_spec.coffee#L158. I'm not certain whether the new fields should be validated in a similar way.

My thinking is to not validate the new fields because an outbound integration should potentially error out if the values are not numbers. That way, the user will still be able to see the value in the UI that tried to get passed rather than null. Thoughts?

### CODE REVIEW

**Comment by cgrayson** [comment]
> Is it a good idea to validate the website passed in mortgage.property.url? Or is that overkill?

As of [earlier today](https://github.com/activeprospect/leadconduit-types/commit/d38590c48457c44ec4bf9da7c0d0de76499a3bd2#diff-76c5f42f6235b9cf5713a3fe721671e3) (or as soon as that's deployed), there is a new `url` type that should be perfect here.

> I'm not certain whether the new fields should be validated in a similar way.

You say "validate", but you linked to a test, so let me know if I'm misunderstanding. IIRC that test was included to make sure the right number of digits was preserved for that incoming floating-point value. So in a "special" case, or when fixing a specific bug, a test case like that might be called for.

**Comment by alexkwolfe** [comment]
> My thinking is to not validate the new fields because an outbound integration should potentially error out if the values are not numbers. That way, the user will still be able to see the value in the UI that tried to get passed rather than null.

I can't quite follow this. You're asking about validating the URL, but talking here about numbers. Either way, values that are invalid are still shown in the UI.

**Comment by ros3bud** [comment]
For the URL issue I will use the URL type for this for the listing URL.

For the second issue of checking for numbers: 
The test I was referring to makes sure that if the value is NaN, null is passed to the internal standard field. https://github.com/activeprospect/leadconduit-integration-leadpoint/blob/master/spec/inbound_spec.coffee#L160. Understood that invalid values are still shown in the UI. 

So, what I'm getting at is: do we want to pass null when a value which is expected to be a number is NaN, or do we let the validate method in the outbound integration return an error message? The reason I'm asking is because the way this is implemented in this integration is not consistent.

**Comment by cgrayson** [comment]
I think a central and valuable function of LeadConduit is standardizing and normalizing data "in the middle", that is, between systems sending it in, and systems that it's being sent out to. As such, I think letting a lead's numeric field get set to `NaN` isn't helpful.

Also, the earlier in the process something can be tidied or dealt with sanely, the better. If inbound integrations clean up whatever they can, then there's less dependence on all the (many) outbound integrations having to include a check for something that's may be a problem.

**Comment by alexkwolfe** [comment]
What is the value of truncating the decimal places of the mortgage interest rate?

**Comment by ros3bud** [comment]
Thanks both of you for the input. I have a good handle on what needs to happen here.

**Comment by ros3bud** [comment]
@alexkwolfe, LGTY? I just wanted to take care of the issue requested for starters. Will add new issues and address those next per our conversation about updating the integration.

**Comment by alexkwolfe** [comment]
LGTM.

**Pull request merged**
