### PR TITLE
Update loan amount

### PR DESCRIPTION
**Pull request by ros3bud**
- Updated mortgage.loan.amount to range type
- removed parseInt 
- added test for range

### CODE REVIEW

**Comment by ros3bud** [comment]
@cgrayson, LGTY?

**Comment by cgrayson** [comment]
:+1:

**Comment by ros3bud** [comment]
Removed test for range and reverted type to number. 

@alexkwolfe, LGTY?

**Comment by alexkwolfe** [comment]
LGTM

**Pull request merged**
